name: CD Pipeline

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Vérifier et lancer docker-compose si disponible
        run: |
          if [ -f "docker-compose.yml" ]; then
            echo "Fichier docker-compose.yml trouvé. Lancement du déploiement."
            docker-compose -f docker-compose.yml up -d --build
          else
            echo "Aucun docker-compose.yml trouvé. Déploiement ignoré."
          fi
